@startuml
'https://plantuml.com/sequence-diagram
'IMS创建流程

participant SystemServer
participant InputManagerService.java
participant WindowManagerService
participant InputManagerService.cpp
participant NativeInputManager.cpp
participant EventHub.cpp
participant InputManager.cpp
participant InputReaderThread
participant InputReader
participant InputDispatcherThread
participant InputDispatcher


activate SystemServer
SystemServer -> SystemServer: main() 系统服务进程主入口
activate SystemServer
SystemServer -> SystemServer: run() 系统服务进程服务启动
activate SystemServer
SystemServer -> SystemServer: startOtherServices() 启动其他服务
activate SystemServer

'创建IMS服务流程
SystemServer -> InputManagerService.java: InputManagerService() 创建IMS服务对象
activate InputManagerService.java
InputManagerService.java -> InputManagerService.java: nativeInit() 调用native方法进行初始化
activate InputManagerService.java
InputManagerService.java -> InputManagerService.cpp: nativeInit() 调用native方法进行初始化
activate InputManagerService.cpp
InputManagerService.cpp -> NativeInputManager.cpp: NativeInputManager() 创建 NativeInputManager 对象
activate NativeInputManager.cpp
NativeInputManager.cpp -> EventHub.cpp: new EventHub()
activate EventHub.cpp
EventHub.cpp --> NativeInputManager.cpp: 创建对象成功
deactivate EventHub.cpp
NativeInputManager.cpp -> InputManager.cpp: new InputManager()
activate InputManager.cpp
InputManager.cpp -> InputDispatcher: new InputDispatcher()
activate InputDispatcher
InputDispatcher --> InputManager.cpp:  创建对象成功
deactivate InputDispatcher
InputManager.cpp -> InputReader: new InputReader(inputDispatcher)
activate InputReader
InputReader --> InputManager.cpp: 创建对象成功
deactivate InputReader
InputManager.cpp -> InputManager.cpp: initialize() 初始化
activate InputManager.cpp
InputManager.cpp -> InputReaderThread: new InputReaderThread()
activate InputReaderThread
InputReaderThread --> InputManager.cpp: 创建成功
deactivate InputReaderThread
InputManager.cpp -> InputDispatcherThread: new InputDispatcherThread()
activate InputDispatcherThread
InputDispatcherThread --> InputManager.cpp: 创建成功
deactivate InputDispatcherThread
InputManager.cpp --> NativeInputManager.cpp: 创建成功
deactivate InputManager.cpp
deactivate InputManager.cpp
NativeInputManager.cpp --> InputManagerService.cpp: 创建成功
deactivate NativeInputManager.cpp
InputManagerService.cpp -->  InputManagerService.java: InputManagerService.java native 初始化成功
deactivate InputManagerService.cpp
InputManagerService.java --> SystemServer: 创建对象成功
deactivate InputManagerService.java
deactivate InputManagerService.java

SystemServer -> WindowManagerService: main()创建WMS服务对象
activate WindowManagerService
WindowManagerService --> SystemServer: 创建对象成功
deactivate WindowManagerService

SystemServer -> SystemServer: addService() 注册服务
activate SystemServer
deactivate SystemServer

SystemServer -> InputManagerService.java: start()启动IMS服务
deactivate SystemServer
deactivate SystemServer
deactivate SystemServer
deactivate SystemServer

'启动服务流程
activate InputManagerService.java



deactivate InputManagerService.java


@enduml