@startuml
'https://plantuml.com/sequence-diagram
'activity 启动（根activity）
autonumber

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml