@startuml
'https://plantuml.com/sequence-diagram
'应用进程启动过程(1)
'Launcher进程向AMS进程发送请求

participant LauncherActivity
participant Activity
participant Instrumentation
participant IActivityManager
participant AMS

'点击桌面图标
LauncherActivity -> LauncherActivity: onListItemClick() 桌面图标点击
note left
        桌面程序Activity
        展示已安装app启动图标
end note
activate LauncherActivity
'包装相关请求参数
LauncherActivity -> Activity: startActivity(Intent intent)，启动Activity
deactivate LauncherActivity

activate Activity
Activity -> Activity: startActivityForResult(Intent intent, int requestCode)
activate Activity
deactivate Activity
Activity -> Activity: startActivityForResult(Intent intent, int requestCode, Bundle options)
activate Activity
Activity -> Instrumentation: execStartActivity()
deactivate Activity
deactivate Activity

'向AMS发送请求
activate Instrumentation
Instrumentation -> IActivityManager: startActivity()
deactivate Instrumentation

activate IActivityManager
IActivityManager -> AMS: startActivity()
note right
    Launcher进程向AMS进程发送请求
end note
deactivate IActivityManager
activate AMS
|||
deactivate AMS

@enduml